---
apiVersion: v1
kind: Service
metadata:
  name: tautulli-farnsworth
  namespace: warehouse20
  labels:
    app: tautulli
    instance: farnsworth
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    targetPort: http
    port: 8181
    protocol: TCP
  selector:
    app: tautulli
    instance: farnsworth
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tautulli-farnsworth
  namespace: warehouse20
  labels:
    app: tautulli
    instance: farnsworth
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.tautulli: glob:v2.*
spec:
  serviceName: tautulli-farnsworth
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tautulli
      instance: farnsworth
  template:
    metadata:
      labels:
        app: tautulli
        instance: farnsworth
    spec:
      automountServiceAccountToken: false
      containers:
      - name: tautulli
        image: "tautulli/tautulli:v2.2.3"
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "950"
        - name: PGID
          value: "950"
        - name: TZ
          value: "America/Chicago"
        ports:
        - containerPort: 8181
          name: http
        resources:
          requests:
            cpu: 200m
            memory: "512Mi"
          limits:
            cpu: 2000m
            memory: "2048Mi"
        volumeMounts:
        - mountPath: /config
          name: config
          subPath: data
        livenessProbe:
          httpGet:
            path: /status
            port: http
          initialDelaySeconds: 300
        readinessProbe:
          httpGet:
            path: /status
            port: http
          initialDelaySeconds: 60
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: tautulli-farnsworth-data
